branches:
  only:
  - master

# before_script:
#   - git config --global user.name "Travis CI"
#   - git config --global user.email "ci@travis-ci.org"

script:
  - bash ./scripts/deploy.sh

# after_success:
#   - ./scripts/auto-deploy.sh

# env:
#   global:
#     - secure: "UCSm2OZkCtH8EPSPjp8fujOyQrtHtPJi8DDdOyCSkUunSw9H+HiONwuh+J1Of77B9OUC1HTWE51tW75nsnaQik4GihXB+eah7ow3RLM14LoLoUz+PA84W8sDuuCbm37Kqtf4vnWKlAUhDeUZNyhGyIezdB22UaqWWir9KGdp4AE="

language: node_js

node_js:
  - "10"

sudo: false

cache: yarn
